Bugfix: find command crashes
AY2425S1-CS2103T-F12-1/tp pull request #83
Opened 2024-10-08 15:44 UTC by lithops-zty

I have noted two cases when the updated `find` command crashes:
- Any of the keyword(s) is empty, e.g. `find n/`
- Any of the keyword(s) contains whitespace(s), e.g. 'find n/Alex Goh'

For a temporary fix, I have rejected both inputs with appropriate error messages. However, the second case may be desired, but requires some deeper investigation into why javafx's FilteredList does not accept multiple-word keywords.

2024-10-10 03:30 UTC, MAOXIONGKAI requested changes
It seems like the issue actually lies within `StringUtil.containsWordIgnoreCase()` method which is used by `NameContainsKeywordsPredicate.java` class. I think instead of the current approach, we should fix the issues by fixing the above two parts of the code first.

2024-10-10 06:37 UTC, lithops-zty commented
@MAOXIONGKAI Thanks for discovering the stem of the issue.

Before revising code, I would like to know how everyone would like our product to behave here.
I suggest the following (Referring to the two scenarios mentioned above):
**for scenario 1:**
Directly reject inputs with at least one empty keyword like `find n/` because it is meaningless. We keep the guard clause within `FindCommandParser.parse()` for this case.

**For scenario 2,**
Allow multi-word keywords. Additionally,
An entry matches a multi-word keyword $keyword_1 keyword_2 \cdots keyword_n$ iff its name $name$ satisfies $\forall i, name.contains(keyword_i)$. In other words, every word in the keyword must be present consecutively in the name, but not necessarily as a full word.

**examples**
Name: `Zhu Tianyi`
|Input|Result|
|------|------|
|`find n\ n\Zhu`|error|
|`find n\Zhu Tian`|match|
|`find n\Tianyi Zhu`|match|
|`find n\Tian Zhu`|match|
|`find n\yiTian`|does not match|


Any alternative suggestion is welcome!

2024-10-10 07:37 UTC, lithops-zty commented
@MAOXIONGKAI Thanks for discovering the stem of the issue. Let's keep it as is for the time being and make allowing multi-word keyword as a nice-to-have to be implemented in the future.

2024-10-11 08:56 UTC, MAOXIONGKAI approved these changes
@lithops-zty  We can accept this for now, but remember to create new issue to fix this bug in a more proper way, thanks

2024-10-11 08:56 UTC, merged